### ISSUE TITLE
FN: No SUSPICIOUS-CONTRACT alert for attack contract

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#301] opened 2023-09-23 21:12 UTC
BOT ID - 0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c
Tx - https://bscscan.com/tx/0xce0e119a317a9e67f37f67e281c546b2cf7df3d4f37e4a660faf245461d49134

**Comment by christian-forta** [comment] 2023-10-19 20:31
@salort-forta , could you pls assess why this contract was classified as safe?

https://explorer.forta.network/alert/0xb3d975985cddf8926116413ee41724855286304998c039cb565dba3872cb1517

{"address_contained_in_created_contract_1":"0x55d398326f99059fF775485246999027B3197955","address_contained_in_created_contract_2":"0x657334B4FF7bDC4143941B1F94301f37659c6281","address_contained_in_created_contract_3":"0x2120F8F305347b6aA5E5dBB347230a8234EB3379","address_contained_in_created_contract_4":"0xFeAFe253802b77456B4627F8c2306a9CeBb5d681","anomaly_score":"0.9020429544264013","model_score":"0.0","model_threshold":"0.5","oko_contract_explorer":"https://oko.palkeo.com/0x1c651B04bDd1C1718EEeafedE0A3c13e87024fa2/"}

**Comment by christian-forta** [comment] 2023-10-27 20:01
@salort-forta , any insights yet?

**Comment by christian-forta** [comment] 2023-11-15 17:01
tested and model not triggering; carlos is investigating why.

**Comment by salort-forta** [comment] 2023-11-23 09:32
What I see here is that the top 10 features of the model, only a couple of them are pushing the prediction towards malicious contract. Since most of the features push the prediction towards non-malicious, it is marked as such. My theory is that this is caused by this model having a different structure than the ones on the training dataset. I would recommend adding this sample for retraining of future iterations of the model.

**Comment by christian-forta** [comment] 2023-11-27 16:49
can you elaborate on what the features are? Can you attach your visualization that shows the weights of the opcode sequences?

**Comment by salort-forta** [comment] 2023-11-28 08:55
![image](https://github.com/forta-network/starter-kits/assets/126703476/ee48dcf0-930e-4951-8dec-5231193f1b96)

**Closed** 2024-04-10 00:07 UTC
Labels: P1, attack detector
