### ISSUE TITLE
Transit finance FN

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#468] opened 2024-01-30 15:17 UTC
In this opportunity we don't have an alert for [this](https://bscscan.com/address/0xf7552ba0eE5BEd0f306658F4A1201f421d703898) attacker. 

There is [an alert](https://app.forta.network/alerts/0xf764c5168e5b8932c2241fa8829b2924a19ff55b46aa4f58e9d9289704fd40dc) though for the beta version, however the metadata does not include the TC funding alert though having [one](https://app.forta.network/alerts/0xaa671e4d049c7de96423bd442e6ab83b66cd8b7e42e29fb6c38db3a159f73940).

**Comment by Thisisgeorg3** [comment] 2024-02-01 01:48
Please investigate the cause for the lack of alert from TC

**Comment by Vxatz** [comment] 2024-02-05 14:12
The reason for the lack of alert from TC is that the funding happened more than 24 hours before the first contract creation alert. This has now been fixed (for intervals up to 10 days).

Regarding the presence of an alert on beta but not on prod, the cause is likely related to a performance issue (as I'm able to receive the alert locally)

**Comment by Thisisgeorg3** [comment] 2024-02-07 00:09
Thank you @Vxatz closing

**Closed by Thisisgeorg3** 2024-02-07 00:09 UTC
Labels: P0, attack detector
