### ISSUE TITLE
FN: No Reentrancy alert for tx

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#298] opened 2023-09-23 18:58 UTC
BOT ID - 0x492c05269cbefe3a1686b999912db1fb5a39ce2e4578ac3951b0542440f435d9
Tx - https://optimistic.etherscan.io/tx/0x3d6367de5c191204b44b8a5cf975f257472087a9aadc59b5d744ffdef33a520e

**Comment by Thisisgeorg3** [comment] 2024-02-01 02:12
Plz reassign if necessary @Vxatz

**Comment by Vxatz** [comment] 2024-02-14 09:57
@Thisisgeorg3 , the issue is that Reentrancy Detector can't work on chains where traces are not supported.

**Closed** 2024-03-15 07:42 UTC
Labels: P2, attack detector
