### ISSUE TITLE
Ice Phishing Detection Bot - FP

### ISSUE THREAD

**Issue by 0xbhagi** [forta-network/starter-kits#503] opened 2024-02-06 12:56 UTC
- Attacker: [0x5399d854863a3fca6a1a7e267a58e81afd920f6f](https://etherscan.io/address/0x5399d854863a3fca6a1a7e267a58e81afd920f6f)
- AD Alert: https://app.forta.network/alerts/0x5dbfcad9e1d43b94339afd5525da20b25e25c44a1e310e91f42816d25325d142
- Base bots:  [Malicious smart contract ml v3](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c) ,[Ice Phishing Detection Bot](https://app.forta.network/bot/0x8badbf2ad65abc3df5b1d9cc388e419d9255ef999fb69aac6bf395646cf01c14), [Unusual Native Swaps Detection Bot](https://app.forta.network/bot/0xabc0bb6fe5e0d0b981dec4aa2337ce91676358c6e8bf1fec06cc558f58c3694e) alerted 
- Potential cause:  base alerts https://app.forta.network/alerts/0x0389e5c9a40590344a5967b5ba7e95f3400f4d6a095c38a48c2bbabe1f41f361 and https://app.forta.network/alerts/0xbb272c457aaad543d8f20b8edf0cf2db71596c9d6ac4d05b6da66aaf8d9ac366 are pointing  0x5399d854863a3fca6a1a7e267a58e81afd920f6f at txn https://etherscan.io/tx/0xde5c171ba4df2f1edefbbfadd9008355b0db1d07e8a8c746dbf9e624a506f9ca as  ICE-PHISHING-SUSPICIOUS-TRANSFER  which is FP, Improvements can be made to Ice Phishing Detection Bot. 
- Idea: A new bot to check Balance Changes on txn's sender and Receiver if there is low % of changes with some condition like Balance Changes is happened only on that contracts addresses which deployer is same  if this is not true do not alert that txn as FP otherwise make that txn FP.

**Comment by Vxatz** [comment] 2024-03-06 15:44
Closing this as the cause was `ICE-PHISHING-SUSPICIOUS-TRANSFER` which has now been removed.

**Closed by Vxatz** 2024-03-06 15:44 UTC
Labels: P2, attack detector
