### ISSUE TITLE
No SUSPICIOUS-CONTRACT alert for malicious contracts

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#328] opened 2023-10-23 09:53 UTC
BOT ID - 0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c

Txs
1)  https://etherscan.io/tx/0xbc863c288a5eaa6bd0bcc411b546828a2b89deb786063b45aaf32ba280a21501

2) https://bscscan.com/tx/0xb76f72341c4cac8ecf8b6a7cfd38cfea6ad48ede0d7a5d891ab62e5fc3a14b4e

**Comment by christian-forta** [comment] 2023-10-27 20:00
@salort-forta , any insights yet?

**Comment by christian-forta** [comment] 2023-11-15 16:59
when running the tx, the model doesnt raise any alert; still investigating why.

**Comment by salort-forta** [comment] 2023-11-23 09:42
For the eth transaction:
What I see here is that the top 10 features of the model, only a couple of them are pushing the prediction towards malicious contract. Since most of the features push the prediction towards non-malicious, it is marked as such. My theory is that this is caused by this model having a different structure than the ones on the training dataset. Also, the importance of the features is quite small in both directions, whereas in attacker contracts the values are much higher.
I would recommend adding this sample for retraining of future iterations of the model.

for the bsc:
top features are benign, and have a much higher importance (as an example, the most important benign feature almost cancels the 3 most important negative). I think this model may have a different structure than the ones used in training.

**Comment by christian-forta** [comment] 2023-11-27 16:48
can you elaborate on what the features are? Can you attach your visualization that shows the weights of the opcode sequences?

**Comment by salort-forta** [comment] 2023-11-28 08:49
0xb76f72341c4cac8ecf8b6a7cfd38cfea6ad48ede0d7a5d891ab62e5fc3a14b4e
![image](https://github.com/forta-network/starter-kits/assets/126703476/07fa5464-3091-4093-9cdb-13bae5093d0a)

0xbc863c288a5eaa6bd0bcc411b546828a2b89deb786063b45aaf32ba280a21501
![image](https://github.com/forta-network/starter-kits/assets/126703476/93495583-75e5-4e23-a670-763cf28b811d)

**Closed** 2024-04-10 00:08 UTC
Labels: P1, attack detector
