### ISSUE TITLE
Ice Phishing bot - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#564] opened 2024-02-29 12:28 UTC
Attacker - [0xa5cf04aa57d7bb4b35210bb5c4fead45e58c545e](https://bscscan.com/address/0xa5cf04aa57d7bb4b35210bb5c4fead45e58c545e)   
Base bots - [malicious-smart-contract](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c), [suspicious-contract-creation](https://app.forta.network/bot/0x457aa09ca38d60410c8ffa1761f535f23959195a56c9b82e0207801e86b34d99), [High Gas](https://app.forta.network/alerts/0x177170bdc5d29ce14625f4ea774bc369fe6f25c5bd24c5e58b77dfebe6a20ee7) and [ICE-PHISHING](https://app.forta.network/bot/0x8badbf2ad65abc3df5b1d9cc388e419d9255ef999fb69aac6bf395646cf01c14)
AD alert - https://app.forta.network/alerts/0xa941852b1df5edb0b10f09ac6cbe3055b9420a58b09eabb0b2052e2f47f544ef
Potential cause - Alert for swaps tx (uniswap)

**Comment by Ivan1905** [comment] 2024-02-29 13:05
@Vxatz I believe the nature of this cause maybe the FP suspicious transfer, WDYT? Once this issue is mitigated we can see if these kind of FPs continue

**Comment by Thisisgeorg3** [comment] 2024-03-05 22:53
@Vxatz will this be relevant with the update to the ice phishing bot or should we close?

**Comment by Vxatz** [comment] 2024-03-06 09:48
Closing this as the cause was `ICE-PHISHING-SUSPICIOUS-TRANSFER` which has now been removed.

**Closed by Vxatz** 2024-03-06 09:48 UTC
Labels: attack detector
