### ISSUE TITLE
 malicious contract v3 + ice-phishing - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#525] opened 2024-02-15 07:49 UTC
Attacker - [0xC3763EAdE23B96Fe6C9F6B9371b144Fe8F1699Ca](https://ftmscan.com/address/0xc3763eade23b96fe6c9f6b9371b144fe8f1699ca)
AD alert - https://app.forta.network/alerts/0xb776770ccd8f780f6daaa0f2f8f5273a0c244de8d0f68a3ffa68694649577b33
Base bots  - [ice phishing](https://app.forta.network/bot/0x8badbf2ad65abc3df5b1d9cc388e419d9255ef999fb69aac6bf395646cf01c14?search=0x8badbf2ad65abc3df5b1d9cc388e419d9255ef999fb69aac6bf395646cf01c14) and [malicious-smart-contract-ml-v3](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c?search=0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c)
Potential cause - the contracts flagged by the malicious contract bot isn't malicious and the ice phishing alerts are false positives

**Comment by Thisisgeorg3** [comment] 2024-02-28 15:42
@Ivan1905 Should we address the Ice Phishing part of this separately?

**Comment by Ivan1905** [comment] 2024-02-28 15:51
This may be linked with [this](https://github.com/forta-network/starter-kits/issues/561) ticket. Apparently the suspicious transfer label is not working as expected. I would say that we first need to review and solve the mentioned alert id.

**Comment by Vxatz** [comment] 2024-03-06 09:49
Closing this as the cause was `ICE-PHISHING-SUSPICIOUS-TRANSFER` which has now been removed.

**Closed by Vxatz** 2024-03-06 09:49 UTC
Labels: attack detector, ML
