### ISSUE TITLE
FP - ICE-PHISHING-SUSPICIOUS-TRANSFER

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#561] opened 2024-02-27 13:25 UTC
Hi there,

Apparently there are FPs coming from this specific label.

e.g:

- [Alert](https://app.forta.network/alerts/0xd2b018101efae69c316a4b2c45130200437a500c2b446265e27f59cda36d1157) it is flagging [this](https://etherscan.io/tx/0xce9629f6bacb8ae203369612de4a0acb8b0bc024d37b0863a7b1bff17965096e) tx.
- [Alert](https://app.forta.network/alerts/0x27fa86bbf905f10b0e6df84df94ccb78b6c1db7af7dcac18590bcdb638eadb79)- tx [here](https://etherscan.io/tx/0xf53a61a485e21c050f4e14f650a59e9bbf590daf66de8d340144ba6646925641)

**Comment by Vxatz** [comment] 2024-03-06 09:49
Closing this as the cause was `ICE-PHISHING-SUSPICIOUS-TRANSFER` which has now been removed.

**Comment by Vxatz** [comment] 2024-03-06 09:49
Closing this as the cause was `ICE-PHISHING-SUSPICIOUS-TRANSFER` which has now been removed.

**Closed by Vxatz** 2024-03-06 09:49 UTC
Labels: P2, scam detector, attack detector
